services:
  app:
    build: .
    env_file:
      - .env.prod
    container_name: node-app
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6.0.16
    container_name: redis-server
